//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Idiomas
    {
        public int ID_HojaVida { get; set; }
        public string Institución { get; set; }
        public string Idioma { get; set; }
        public string NOral { get; set; }
        public string NEscrito { get; set; }
        public string NLectura { get; set; }
    
        public virtual Hoja_Vida Hoja_Vida { get; set; }
    }
}
